[package]
name = "cap-lab-daemon"
version = "0.1.0"
edition = "2021"

[dependencies]
cap-lab-interface = { path = "../cap-lab-interface" }
actix-web = "4"
tokio = { version = "1", features = ["full"] }
caps = "0.5"
