[package]
name = "cap-lab-client"
version = "0.1.0"
edition = "2021"

[dependencies]
structopt = "0.3"
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1", features = ["full"] }
